# permissions for end users to edit hanamappings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: hanamapping-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: hana-mapping-operator
    app.kubernetes.io/part-of: hana-mapping-operator
    app.kubernetes.io/managed-by: kustomize
  name: hanamapping-editor-role
rules:
- apiGroups:
  - hana.cloud.sap.com
  resources:
  - hanamappings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hana.cloud.sap.com
  resources:
  - hanamappings/status
  verbs:
  - get
